# Generated by Django 4.0.3 on 2022-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emailid', models.EmailField(max_length=255)),
                ('fullname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
